INSERT INTO restaurants (title, address, opening_hours)
VALUES
    ('Le Comptoir du Relais', '9 Carrefour de l''Odéon, 75006 Paris', '12:00-23:00'),
    ('Bouillon Pigalle', '22 Boulevard de Clichy, 75018 Paris', '12:00-00:00'),
    ('Pink Mamma', '20bis Rue de Douai, 75009 Paris', '12:00-14:15 / 18:00-23:00'),
    ('Kodawari Ramen Yokochō', '29 Rue Mazarine, 75006 Paris', '11:45-23:00'),
    ('L''As du Fallafel', '34 Rue des Rosiers, 75004 Paris', '11:00-23:30'),
    ('Frenchie', '5 Rue du Nil, 75002 Paris', '18:30-22:30'),
    ('Breizh Café', '109 Rue Vieille du Temple, 75003 Paris', '09:00-23:00'),
    ('Bistrot Paul Bert', '18 Rue Paul Bert, 75011 Paris', '12:00-14:00 / 19:30-22:30'),
    ('Les Papilles', '30 Rue Gay-Lussac, 75005 Paris', '12:00-14:00 / 18:30-22:00'),
    ('Bouillon Chartier Grands Boulevards', '7 Rue du Faubourg Montmartre, 75009 Paris', '11:30-00:00'),
    ('Francette', '1 Port de Suffren, 75007 Paris', '12:00-00:00'),
    ('La Jacobine', '59-61 Rue Saint-André des Arts, 75006 Paris', '12:00-16:30 / 19:00-22:30'),
    ('Il Grano', '212 Bis Boulevard Pereire, 75017 Paris', '11:30-23:00'),
    ('Restaurant japonais LA MARINA', '18 Rue de la Michodière, 75002 Paris', '11:30-15:30 / 18:30-23:00'),
    ('Yansai', '88 Rue des Gravilliers, 75003 Paris', '11:45-14:30 / 18:45-22:15'),
    ('Le Cinq', '31 Avenue George V, 75008 Paris', '19:00-21:30'),
    ('Sacrée Fleur Montmartre', '50 Rue de Clignancourt, 75018 Paris', '18:00-22:00'),
    ('La Padellina', '1 Rue Chaptal, 75009 Paris', '12:00-14:30 / 18:30-23:00'),
    ('Kanpai Paris', '19 Rue Bréa, 75006 Paris', '12:00-14:45 / 19:00-22:30'),
    ('La Taverne De ZHAO', '22 Rue Molière, 75001 Paris', '12:00-22:30'),
    ('Le Vieux Bistrot', '54 Rue Mouffetard, 75005 Paris', '12:00-23:00'),
    ('Clamato', '80 Rue de Charonne, 75011 Paris', '12:00-14:30 / 19:00-22:30'),
    ('Septime', '80 Rue de Charonne, 75011 Paris', '12:15-14:00 / 19:30-23:00'),
    ('Le Train Bleu', 'Gare de Lyon, Place Louis Armand, 75012 Paris', '11:15-14:30 / 19:00-22:30'),
    ('Chez Janou', '2 Rue Roger Verlomme, 75003 Paris', '08:30-02:00'),
    ('Le Servan', '32 Rue Saint-Maur, 75011 Paris', '12:00-14:00 / 19:30-22:30'),
    ('Miznon Marais', '22 Rue des Écouffes, 75004 Paris', '12:00-23:00'),
    ('YOOM dim sum Rive Gauche', '5 Rue Grégoire de Tours, 75006 Paris', '12:00-14:30 / 18:30-22:30'),
    ('Le Relais du Louvre', '3 Rue du Louvre, 75001 Paris', '07:00-23:00'),
    ('Le Poulbot', '3 Rue Poulbot, 75018 Paris', '12:00-22:00'),
    ('Le Ju''', '16 Rue des Archives, 75004 Paris', '07:00-02:00'),
    ('Le Rempart Bastille', '15 Rue Saint-Antoine, 75004 Paris', '07:00-00:00'),
    ('Café de Flore', '172 Boulevard Saint-Germain, 75006 Paris', '07:30-01:30'),
    ('Les Deux Magots', '6 Place Saint-Germain des Prés, 75006 Paris', '07:30-01:00'),
    ('Benoit Paris', '20 Rue Saint-Martin, 75004 Paris', '12:00-14:00 / 19:00-22:00'),
    ('Le Grand Véfour', '17 Rue de Beaujolais, 75001 Paris', '12:00-14:00 / 19:00-22:00'),
    ('Restaurant Le Jules Verne', 'Tour Eiffel, Avenue Gustave Eiffel, 75007 Paris', '12:00-13:45 / 19:00-20:45'),
    ('Le Clarence', '31 Avenue Franklin Delano Roosevelt, 75008 Paris', '12:30-13:30 / 19:30-21:00'),
    ('Arpège', '84 Rue de Varenne, 75007 Paris', '12:00-14:30 / 19:30-22:30'),
    ('L''Ambroisie', '9 Place des Vosges, 75004 Paris', '12:15-13:15 / 20:00-21:15'),
    ('Restaurant Pierre Gagnaire', '6 Rue Balzac, 75008 Paris', '12:00-13:30 / 19:30-21:30'),
    ('Pizzeria Popolare', '111 Rue Réaumur, 75002 Paris', '11:45-14:15 / 18:00-22:15'),
    ('Ober Mamma', '107 Boulevard Richard-Lenoir, 75011 Paris', '12:00-14:30 / 18:15-22:30'),
    ('East Mamma', '133 Rue du Faubourg Saint-Antoine, 75011 Paris', '12:00-14:15 / 18:15-22:15'),
    ('Candelaria', '52 Rue de Saintonge, 75003 Paris', '15:00-02:00'),
    ('Hakata Choten OPERA', '53 Rue des Petits Champs, 75001 Paris', '12:00-15:00 / 18:00-22:00'),
    ('Sanukiya', '9 Rue d''Argenteuil, 75001 Paris', '11:30-22:00'),
    ('YOOM dim sum Rive Droite', '20 Rue des Martyrs, 75009 Paris', '12:00-14:30 / 18:30-22:00'),
    ('Le Petit Cler', '29 Rue Cler, 75007 Paris', '08:00-00:00'),
    ('Restaurant Le Coupe-Chou', '11 Rue de Lanneau, 75005 Paris', '18:30-22:30');

INSERT INTO app_users (name, email)
VALUES
    ('Alice Martin', 'alice.martin@example.com'),
    ('Lucas Bernard', 'lucas.bernard@example.com'),
    ('Emma Dubois', 'emma.dubois@example.com'),
    ('Hugo Moreau', 'hugo.moreau@example.com'),
    ('Chloé Laurent', 'chloe.laurent@example.com'),
    ('Louis Simon', 'louis.simon@example.com'),
    ('Camille Michel', 'camille.michel@example.com'),
    ('Gabriel Garcia', 'gabriel.garcia@example.com'),
    ('Manon Leroy', 'manon.leroy@example.com'),
    ('Arthur Roux', 'arthur.roux@example.com'),
    ('Léa David', 'lea.david@example.com'),
    ('Nathan Bertrand', 'nathan.bertrand@example.com'),
    ('Inès Fontaine', 'ines.fontaine@example.com'),
    ('Thomas Chevalier', 'thomas.chevalier@example.com'),
    ('Sarah Robin', 'sarah.robin@example.com'),
    ('Jules Masson', 'jules.masson@example.com'),
    ('Clara Henry', 'clara.henry@example.com'),
    ('Maxime Girard', 'maxime.girard@example.com'),
    ('Zoé André', 'zoe.andre@example.com'),
    ('Antoine Mercier', 'antoine.mercier@example.com'),
    ('Julie Dupont', 'julie.dupont@example.com'),
    ('Paul Bonnet', 'paul.bonnet@example.com'),
    ('Nina François', 'nina.francois@example.com'),
    ('Thomas Garnier', 'thomas.garnier@example.com'),
    ('Eva Faure', 'eva.faure@example.com'),
    ('Romain Legrand', 'romain.legrand@example.com'),
    ('Louise Gauthier', 'louise.gauthier@example.com'),
    ('Mathis Perrin', 'mathis.perrin@example.com'),
    ('Anaïs Chevalier', 'anais.chevalier@example.com'),
    ('Victor Marchand', 'victor.marchand@example.com'),
    ('Margot Rolland', 'margot.rolland@example.com'),
    ('Éthan Colin', 'ethan.colin@example.com'),
    ('Charlotte Barbier', 'charlotte.barbier@example.com'),
    ('Noah Aubert', 'noah.aubert@example.com'),
    ('Lucie Renard', 'lucie.renard@example.com'),
    ('Arthur Lambert', 'arthur.lambert@example.com'),
    ('Jeanne Renaud', 'jeanne.renaud@example.com'),
    ('Alexandre Leclerc', 'alexandre.leclerc@example.com'),
    ('Mia Olivier', 'mia.olivier@example.com'),
    ('Théo Guillon', 'theo.guillon@example.com'),
    ('Alice Perrier', 'alice.perrier@example.com'),
    ('Sacha Vidal', 'sacha.vidal@example.com'),
    ('Élise Brun', 'elise.brun@example.com'),
    ('Martin Noel', 'martin.noel@example.com'),
    ('Agathe Rey', 'agathe.rey@example.com'),
    ('Benjamin Dumas', 'benjamin.dumas@example.com'),
    ('Louise Meunier', 'louise.meunier@example.com'),
    ('Hugo Marchal', 'hugo.marchal@example.com'),
    ('Clémence Pelletier', 'clemence.pelletier@example.com'),
    ('Raphaël Boucher', 'raphael.boucher@example.com');

INSERT INTO reviews (rating, summary, details, user_id, restaurant_id)
VALUES
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 8, 1),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 19, 1),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 30, 1),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 41, 1),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 2, 1),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 13, 1),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 24, 1),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 35, 1),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats. Le côté traditionnel et le prix raisonnable sont appréciables.', 15, 2),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Le côté traditionnel et le prix raisonnable sont appréciables.', 26, 2),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé. Le côté traditionnel et le prix raisonnable sont appréciables.', 37, 2),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées. Le côté traditionnel et le prix raisonnable sont appréciables.', 48, 2),
    (4, 'Bon moment', 'Service agréable et ambiance plaisante. Le côté traditionnel et le prix raisonnable sont appréciables.', 9, 2),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats. Le côté traditionnel et le prix raisonnable sont appréciables.', 20, 2),
    (4, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Le côté traditionnel et le prix raisonnable sont appréciables.', 31, 2),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent. Les saveurs italiennes étaient bien présentes.', 22, 3),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé. Les saveurs italiennes étaient bien présentes.', 33, 3),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent. Les saveurs italiennes étaient bien présentes.', 44, 3),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante. Les saveurs italiennes étaient bien présentes.', 5, 3),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent. Les saveurs italiennes étaient bien présentes.', 16, 3),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Les saveurs italiennes étaient bien présentes.', 27, 3),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé. Les nouilles étaient un point fort du repas.', 29, 4),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées. Les nouilles étaient un point fort du repas.', 40, 4),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante. Les nouilles étaient un point fort du repas.', 1, 4),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats. Les nouilles étaient un point fort du repas.', 12, 4),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Les nouilles étaient un point fort du repas.', 23, 4),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé. Les nouilles étaient un point fort du repas.', 34, 4),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 36, 5),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 47, 5),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 8, 5),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 19, 5),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 30, 5),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 43, 6),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 4, 6),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 15, 6),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 26, 6),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 37, 6),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 50, 7),
    (4, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 11, 7),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 22, 7),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 33, 7),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 7, 8),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent.', 18, 8),
    (4, 'Bon moment', 'Service agréable et ambiance plaisante. Le côté traditionnel et le prix raisonnable sont appréciables.', 32, 10),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats. Le côté traditionnel et le prix raisonnable sont appréciables.', 43, 10),
    (4, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Le côté traditionnel et le prix raisonnable sont appréciables.', 4, 10),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé. Le côté traditionnel et le prix raisonnable sont appréciables.', 15, 10),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées. Le côté traditionnel et le prix raisonnable sont appréciables.', 26, 10),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 28, 11),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 39, 11),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 50, 11),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 35, 12),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 46, 12),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 7, 12),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent. Les saveurs italiennes étaient bien présentes.', 42, 13),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé. Les saveurs italiennes étaient bien présentes.', 3, 13),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 49, 14),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 10, 14),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 21, 14),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées. Les plats asiatiques étaient parfumés et bien présentés.', 6, 15),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante. Les plats asiatiques étaient parfumés et bien présentés.', 17, 15),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 13, 16),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 24, 16),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 20, 17),
    (4, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 31, 17),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 42, 17),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 3, 17),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Les saveurs italiennes étaient bien présentes.', 27, 18),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent. Les saveurs italiennes étaient bien présentes.', 38, 18),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 34, 19),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 45, 19),
    (4, 'Bon moment', 'Service agréable et ambiance plaisante.', 6, 19),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées. Les plats asiatiques étaient parfumés et bien présentés.', 41, 20),
    (4, 'Bon moment', 'Service agréable et ambiance plaisante. Les plats asiatiques étaient parfumés et bien présentés.', 2, 20),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats. Les plats asiatiques étaient parfumés et bien présentés.', 13, 20),
    (4, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Les plats asiatiques étaient parfumés et bien présentés.', 24, 20),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 48, 21),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 9, 21),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 5, 22),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 16, 22),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 27, 22),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent.', 12, 23),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 23, 23),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent.', 34, 23),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 45, 23),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent.', 6, 23),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 19, 24),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 30, 24),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 41, 24),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 2, 24),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 26, 25),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 37, 25),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 48, 25),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 33, 26),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 44, 26),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 5, 26),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 40, 27),
    (4, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 1, 27),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 12, 27),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 23, 27),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Les plats asiatiques étaient parfumés et bien présentés.', 47, 28),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent. Les plats asiatiques étaient parfumés et bien présentés.', 8, 28),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées. Les plats asiatiques étaient parfumés et bien présentés.', 19, 28),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 4, 29),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 15, 29),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 11, 30),
    (4, 'Bon moment', 'Service agréable et ambiance plaisante.', 22, 30),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 33, 30),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 18, 31),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 29, 31),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 25, 32),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 36, 32),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent.', 32, 33),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 43, 33),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent.', 4, 33),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 15, 33),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 39, 34),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 50, 34),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 11, 34),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 46, 35),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 7, 35),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 18, 35),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 3, 36),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 14, 36),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 10, 37),
    (4, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 21, 37),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 32, 37),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 43, 37),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 17, 38),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent.', 28, 38),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé.', 24, 39),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 35, 39),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 31, 40),
    (4, 'Bon moment', 'Service agréable et ambiance plaisante.', 42, 40),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 38, 41),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision.', 49, 41),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité.', 10, 41),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats. Les saveurs italiennes étaient bien présentes.', 45, 42),
    (5, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Les saveurs italiennes étaient bien présentes.', 6, 42),
    (4, 'Service efficace', 'Le service était attentif et le repas bien organisé. Les saveurs italiennes étaient bien présentes.', 17, 42),
    (5, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées. Les saveurs italiennes étaient bien présentes.', 28, 42),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent. Les saveurs italiennes étaient bien présentes.', 2, 43),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé. Les saveurs italiennes étaient bien présentes.', 13, 43),
    (2, 'Mitigé', 'La cuisine était intéressante mais le service était un peu lent. Les saveurs italiennes étaient bien présentes.', 24, 43),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante. Les saveurs italiennes étaient bien présentes.', 35, 43),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé. Les saveurs italiennes étaient bien présentes.', 9, 44),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées. Les saveurs italiennes étaient bien présentes.', 20, 44),
    (4, 'Cuisine réussie', 'Les plats étaient bien exécutés et les saveurs équilibrées.', 16, 45),
    (5, 'Bon moment', 'Service agréable et ambiance plaisante.', 27, 45),
    (4, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats.', 38, 45),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision. Les nouilles étaient un point fort du repas.', 23, 46),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats. Les nouilles étaient un point fort du repas.', 34, 46),
    (3, 'Correct', 'Le repas était correct mais certains détails manquaient de précision. Les nouilles étaient un point fort du repas.', 45, 46),
    (5, 'Service efficace', 'Le service était attentif et le repas bien organisé. Les nouilles étaient un point fort du repas.', 6, 46),
    (5, 'À refaire', 'Nous avons particulièrement apprécié la qualité des plats. Les nouilles étaient un point fort du repas.', 30, 47),
    (4, 'Très bonne découverte', 'Belle expérience culinaire et produits de qualité. Les nouilles étaient un point fort du repas.', 41, 47);


